name: release
on:
  push:
    tags:
    - 'v*.*.*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: digitalocean/mako-home-site
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: build/site/Dockerfile
        tag_names: true